### ISSUE TITLE
Plain Text File vs. Document Files

### ISSUE THREAD

**Issue by rodrigih** [rodrigih/GTK-text#2]
Does the text editor create plain text files or Document files?

**Comment by kevdez** [comment]
Plain text files. It should handle anything in some character encoding, UTF-8 most likely. So it should read anything in .txt, or .py or .java or .cpp, etc. Files like .doc, should be read as some compiled byte stuff, like when you open a .doc with Notepad.

Text editors always work with plain text. (Notepad, Sublime, vim)
Word processors work with Document files, which have a certain undercover format, with headers and metadata stuff. Word processors are more complex to make. (M$ Word, LibreOffice, OpenOffice)
